apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-html
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-html
  template:
    metadata:
      labels:
        app: nginx-html
    spec:
      containers:
      - name: nginx
        image: santi/nginx-html:v2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-html-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80